const Zapatos = [
    {
        id: 1,
        name: 'LERA BLACK',
        price: 53.099,
        img: './img/botas/botas1.jpg',
        category: 'botas',
    },
    {
        id: 2,
        name: 'YAMINA ROJO',
        price: 44.444,
        img: './img/botas/botas2.webp',
        category: 'botas',
    },
    {
        id: 3,
        name: 'LERA NEON',
        price: 53.099,
        img: './img/botas/botas3.jpg',
        category: 'botas',
    },
    {
        id: 4,
        name: 'MARGIT JEAN',
        price: 25.159,
        img: './img/botas/botas4.webp',
        category: 'botas',
    },
    {
        id: 5,
        name: 'YAMINA AZUL',
        price: 44.444,
        img: './img/botas/botas5.webp',
        category: 'botas',
    },
    {
        id: 6,
        name: 'ZARIA BLACK',
        price: 37.999,
        img: './img/botas/botas6.webp',
        category: 'botas',
    },
    {
        id: 7,
        name: 'YAMINA AMARILLO',
        price: 44.444,
        img: './img/botas/botas7.webp',
        category: 'botas',
    },
    {
        id: 8,
        name: 'LERA WHITE',
        price: 53.099,
        img: './img/botas/botas8.webp',
        category: 'botas',
    },
    {
        id: 9,
        name: 'NABILA AZUL',
        price: 47.999,
        img: './img/botas/botas9.webp',
        category: 'botas',
    },
    {
        id: 10,
        name: 'NABILA AMARILLO',
        price: 47.999,
        img: './img/botas/botas10.webp',
        category: 'botas',
    },
    {
        id: 11,
        name: 'AMAL ROJO',
        price: 27.199,
        img: './img/botas/botas11.webp',
        category: 'botas',
    },
    {
        id: 12,
        name: 'LERA AZUL METAL',
        price: 53.099,
        img: './img/botas/botas12.webp',
        category: 'botas',
    },
    {
        id: 13,
        name: 'LERA PLATA',
        price: 53.099,
        img: './img/botas/botas13.webp',
        category: 'botas',
    },
    {
        id: 14,
        name: 'LERA ROJO',
        price: 53.099,
        img: './img/botas/botas14.webp',
        category: 'botas',
    },
    {
        id: 15,
        name: 'INESA VIOLETA',
        price: 26.999,
        img: './img/botas/botas15.webp',
        category: 'botas',
    },
    {
        id: 16,
        name: 'ZARIA SUELA',
        price: 37.999,
        img: './img/botas/botas16.webp',
        category: 'botas',
    },
    {
        id: 17,
        name: 'ZARIA ROJO',
        price: 37.999,
        img: './img/botas/botas17.webp',
        category: 'botas',
    },
    {
        id: 18,
        name: 'RUTH BLACK',
        price: 29.059,
        img: './img/cañabaja/cañabaja1.jpg',
        category: 'cañabaja',
    },
    {
        id: 19,
        name: 'ZEITA BLACK',
        price: 33.002,
        img: './img/cañabaja/cañabaja2.webp',
        category: 'cañabaja',
    },
    {
        id: 20,
        name: 'KANDE LILA',
        price: 24.799,
        img: './img/cañabaja/cañabaja3.webp',
        category: 'cañabaja',
    },
    {
        id: 21,
        name: 'KANDE PLATA',
        price: 24.799,
        img: './img/cañabaja/cañabaja4.jpg',
        category: 'cañabaja',
    },
    {
        id: 22,
        name: 'KANDE JEAN',
        price: 24.799,
        img: './img/cañabaja/cañabaja5.webp',
        category: 'cañabaja',
    },
    {
        id: 23,
        name: 'BEGUM TURQUESA',
        price: 46.199,
        img: './img/sandalias/sandalias.jpg',
        category: 'sandalias',
    },
    {
        id: 24,
        name: 'ZETTA',
        price: 22.999,
        img: './img/sandalias/sandalias1.jpg',
        category: 'sandalias',
    },
    {
        id: 25,
        name: 'IRIA PRINT',
        price: 21.059,
        img: './img/sandalias/sandalias2.jpg',
        category: 'sandalias',
    },
    {
        id: 26,
        name: 'IRIA NARANJA REPTIL',
        price: 21.059,
        img: './img/sandalias/sandalias3.jpg',
        category: 'sandalias',
    },
    {
        id: 27,
        name: 'IRIA VERDE BOA',
        price: 21.059,
        img: './img/sandalias/sandalias4.jpg',
        category: 'sandalias',
    },
    {
        id: 28,
        name: 'IZABEL',
        price: 23.399,
        img: './img/sandalias/sandalias5.jpg',
        category: 'sandalias',
    },
    {
        id: 29,
        name: 'IRIA BLACK',
        price: 21.059,
        img: './img/sandalias/sandalias6.jpg',
        category: 'sandalias',
    },
    {
        id: 30,
        name: 'VARYA REPTIL BLACK',
        price: 19.999,
        img: './img/sandalias/sandalias7.jpg',
        category: 'sandalias',
    },
    {
        id: 31,
        name: 'IRIA ZEBRA',
        price: 21.059,
        img: './img/sandalias/sandalias8.jpg',
        category: 'sandalias',
    },
    {
        id: 32,
        name: 'BEGUM FUCSIA',
        price: 46.199,
        img: './img/sandalias/sandalias9.webp',
        category: 'sandalias',
    },
    {
        id: 33,
        name: 'ZETTA BLACK',
        price: 22.372,
        img: './img/sandalias/sandalias10.webp',
        category: 'sandalias',
    },
    {
        id: 34,
        name: 'LUCY BLACK CROCO',
        price: 20.099,
        img: './img/sandalias/sandalias11.webp',
        category: 'sandalias',
    },
    {
        id: 35,
        name: 'LUCY WHITE',
        price: 20.099,
        img: './img/sandalias/sandalias12.jpg',
        category: 'sandalias',
    },
    {
        id: 36,
        name: 'LEWA ZEBRA',
        price: 25.322,
        img: './img/sandalias/sandalias13.jpg',
        category: 'sandalias',
    },
    {
        id: 37,
        name: 'ALANE VERDE',
        price: 6.299,
        img: './img/sandalias/sandalias14.png',
        category: 'sandalias',
    }, 
    {
        id: 38,
        name: 'TARA PLATA',
        price: 34.199,
        img: './img/texanas/texanas.webp',
        category: 'texanas',
    },
    {
        id: 39,
        name: 'TARA WHITE',
        price: 34.199,
        img: './img/texanas/texanas1.jpg',
        category: 'texanas',
    },
    {
        id: 40,
        name: 'TARA ORO',
        price: 34.199,
        img: './img/texanas/texanas2.jpg',
        category: 'texanas',
    },
    {
        id: 41,
        name: 'LEI',
        price: 6.651,
        img: './img/sale/sale.jpg',
        category: 'sale',
    },
    {
        id: 42,
        name: 'LESLIE',
        price: 4.299,
        img: './img/sale/sale1.jpeg',
        category: 'sale',
    },
    {
        id: 43,
        name: 'BELL',
        price: 5.999,
        img: './img/sale/sale2.jpg',
        category: 'sale',
    },
    {
        id: 44,
        name: 'ALESKA',
        price: 4.999,
        img: './img/sale/sale3.jpeg',
        category: 'sale',
    },
    {
        id: 45,
        name: 'CITRA',
        price: 4.989,
        img: './img/sale/sale4.jpg',
        category: 'sale',
    },
]

const splitProducts = (size) => {
    let dividedProducts = [];
    for (let i = 0; i < Zapatos.length; i += size)
      dividedProducts.push(Zapatos.slice(i, i + size));
    return dividedProducts;
};
  
const productsController = {
    dividedProducts: splitProducts(8),
    nextProductsIndex: 1,
    productsLimit: splitProducts(8).length,
};